apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kvm-fuse  # 已修改 VM 名称
  namespace: kvm-builder-dev
spec:
  dataVolumeTemplates:
  - metadata:
      name: kvm-fuse  # 已同步修改 DataVolume 名称
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: rook-ceph-block
        volumeMode: Block
      source:
        snapshot:
          name: pvc-cubjdrtvf-s
          namespace: ""
  running: true
  template:
    metadata:
      labels:
        userId: "3625"
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: userId
                operator: In
                values:
                - "3625"
            topologyKey: kubernetes.io/hostname
      architecture: amd64
      domain:
        clock:
          timezone: Asia/Shanghai
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          inputs:
          - bus: virtio
            name: tablet1
            type: tablet
          interfaces:
          - bridge: {}
            name: bridge
          - bridge: {}
            name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: "2"
            memory: 5Gi
          requests:
            cpu: "2"
            memory: 4Gi
      networks:
      - multus:
          networkName: br-14b78cfmx
        name: bridge
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: kvm-fuse  # 已同步修改关联的 DataVolume 名称
        name: rootdisk
              - name: cloudinitdisk
        cloudInitNoCloud:  
          userData: |
            #cloud-config
            disable_root: false
            user: root
            password: 123456
            chpasswd:
              expire: false
            ssh_pwauth: true
            ssh_authorized_keys:
            package_update: true
            package_upgrade: false
            packages:
              - s3fs
              - fuse
              - s3fs-fuse
            write_files:
            - path: /etc/.passwd-s3fs
              content: VTSFCESQB139A2AD10W0:PhCw6oSgVKKacxATZtNoMug7kJOJUd6xDCeJSxr3
              permissions: '0600'
            - path: /etc/fuse.conf
              content: |
                user_allow_other
              permissions: '0644'
            mounts:
              - [ "s3fs#test", "/data", "fuse", "url=https://s3.dev.tiusolution.com,passwd_file=/etc/.passwd-s3fs,use_path_request_style,allow_other,ssl_verify_hostname=0", "0", "0" ]
            runcmd:
              - mkdir -p /data
              - s3fs test /data -o passwd_file=/etc/.passwd-s3fs -o url=https://s3.dev.tiusolution.com -o use_path_request_style -o ssl_verify_hostname=0 -o nonempty

# password明文会泄露，可生成哈希值openssl passwd -6 -salt salt12345 123456 或 python3 -c "import crypt; print(crypt.crypt('123456', crypt.mksalt(crypt.METHOD_SHA512)))"
# ssh_pwauth: true显式启用，使得可通过ssh ubuntu@ip + 密码登录

# kubectl apply -f kvm-fuse.yaml -n kvm-builder-dev

# kubectl virt console kvm-fuse -n kvm-builder-dev

# virtctl console kvm-fuse -n kvm-builder-dev
