apiVersion: v1
kind: Pod
metadata:
  name: student-pod-01
spec:
  containers:
  - name: student-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: workdir
      mountPath: /mnt
  volumes:
  - name: workdir
    ephemeral:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          dataSource:
            name: base-snapshot
            kind: VolumeSnapshot
            apiGroup: snapshot.storage.k8s.io
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

# kubectl apply -f student-lab-snapshot.yaml -n rens-test
# kubectl exec -it student-pod-01 -n rens-test -- sh

# kubectl get pods -n rens-test
# kubectl get pvc -n rens-test
# kubectl delete pod student-pod-01 -n rens-test